(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["CompoundAnd"]
PackageExport["CompoundOr"]


CompoundAnd::usage="CompoundAnd[\!\(\*
StyleBox[\"conds\", \"TI\"]\)] is True if all \!\(\*
StyleBox[\"conds\", \"TI\"]\) are True.";


CompoundAnd[list_]:=Module[{},And[Evaluate[Sequence@@list]]];


CompoundOr::usage="CompoundOr[\!\(\*
StyleBox[\"conds\", \"TI\"]\)] is True if any of \!\(\*FormBox[
StyleBox[\"conds\", \"TI\"],
TraditionalForm]\) are True.";


CompoundOr[list_]:=Module[{},Or[Evaluate[Sequence@@list]]];
