(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["EqSort"]


EqSort::usage=
"EqSort[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] sorts \!\(\*
StyleBox[\"rulelist\", \"TI\"]\) in order of increasing number of non-zero entries.";


(*EqSort[x_?RuleListListQ]:=SortBy[x,Reverse[Map[If[Abs[#]<$MachineEpsilon,0,1]&,#\[LeftDoubleBracket]All,2\[RightDoubleBracket]]]&];*)
EqSort[x_?RuleListListQ]:=Module[{ind},ind[y_]:=Reverse[Map[If[Abs[#[[2]]]<$MachineEpsilon,0,1,1]&,y]];SortBy[x,{Total[ind[#]]&,ind[#]&}]];


EqSort[x_?RuleListQ]:=x;
