(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ExtractInterpolatingFunctionPoints"]


ExtractInterpolatingFunctionPoints::usage="ExtractInterpolatingFunctionPoints[\!\(\*
StyleBox[\"if\", \"TI\"]\)] extracts the points from InterpolatingFunction \!\(\*
StyleBox[\"if\", \"TI\"]\).";


ExtractInterpolatingFunctionPoints[if_InterpolatingFunction]:=Flatten[Table[
Table[{Sequence@@el[[1]],el2},{el2,Flatten[{el[[2]]}]}],
{el,Transpose[{if["Grid"],if["ValuesOnGrid"]}]}],1]


(* thread over RuleLists *)
ExtractInterpolatingFunctionPoints[f_?TemporalRuleListQ]:=f/.(x_->val_):>(x->ExtractInterpolatingFunctionPoints[val]);



