(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["FinalDerivatives"]


FinalDerivatives::usage=
"FinalDerivatives[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] replaces temporal \!\(\*
StyleBox[\"rulelist\", \"TI\"]\) with their final derivatives.
FinalDerivatives[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\), \!\(\*
StyleBox[\"\[Delta]\", \"TI\"]\)] averages over the final values starting at \!\(\*
StyleBox[\"\[Delta]\", \"TI\"]\).";


FinalDerivatives[sol_?TemporalRuleListQ,dtin_:0]:=Module[{res},
	If[dtin===All,dt=FinalTime[sol],dt=dtin];
	If[dt==0,
		res=Which[
			Head[#[[2]]]===InterpolatingFunction,
			ReplacePart[#,{1->#[[1]]',2->(#[[1]]'[#[[2,1,1,2]]]/.#)}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]1\[RightDoubleBracket]'[#\[LeftDoubleBracket]2,1,1,2\[RightDoubleBracket]]/.#)}]*)
		,
			Head[#[[2]]]===List,
			ReplacePart[#,{1->#[[1]]',2->(#[[2,-1,2]]-#[[2,-2,2]])/(#[[2,-1,1]]-#[[2,-2,1]])}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]2,-1,2\[RightDoubleBracket]-#\[LeftDoubleBracket]2,-2,2\[RightDoubleBracket])/(#\[LeftDoubleBracket]2,-1,1\[RightDoubleBracket]-#\[LeftDoubleBracket]2,-2,1\[RightDoubleBracket])}]*)
		,
			Head[#[[2]]]===TemporalData,
			ReplacePart[#,{1->#[[1]]',2->(#[[2]]["Values"][[-1]]-#[[2]]["Values"][[-2]])/(#[[2]]["Times"][[-1]]-#[[2]]["Times"][[-2]])}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]2\[RightDoubleBracket]["Values"]\[LeftDoubleBracket]-1\[RightDoubleBracket]-#\[LeftDoubleBracket]2\[RightDoubleBracket]["Values"]\[LeftDoubleBracket]-2\[RightDoubleBracket])/(#\[LeftDoubleBracket]2\[RightDoubleBracket]["Times"]\[LeftDoubleBracket]-1\[RightDoubleBracket]-#\[LeftDoubleBracket]2\[RightDoubleBracket]["Times"]\[LeftDoubleBracket]-2\[RightDoubleBracket])}]*)
		,
			Else,#
		]&/@sol
	,
		res=Which[
			Head[#[[2]]]===InterpolatingFunction,
			ReplacePart[#,{1->#[[1]]',2->(#[[1]][#[[2,1,1,2]]]-#[[1]][#[[2,1,1,2]]-dt])/dt/.#}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]1\[RightDoubleBracket][#\[LeftDoubleBracket]2,1,1,2\[RightDoubleBracket]]-#\[LeftDoubleBracket]1\[RightDoubleBracket][#\[LeftDoubleBracket]2,1,1,2\[RightDoubleBracket]-dt])/dt/.#}]*)
		,
			Head[#[[2]]]===List,
			ReplacePart[#,{1->#[[1]]',2->(#[[2,-1,2]]-#[[2,-(1+dt),2]])/(#[[2,-1,1]]-#[[2,-(1+dt),1]])}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]2,-1,2\[RightDoubleBracket]-#\[LeftDoubleBracket]2,-(1+dt),2\[RightDoubleBracket])/(#\[LeftDoubleBracket]2,-1,1\[RightDoubleBracket]-#\[LeftDoubleBracket]2,-(1+dt),1\[RightDoubleBracket])}]*)
		,
			Head[#[[2]]]===TemporalData,
			ReplacePart[#,{1->#[[1]]',2->(#[[2]]["Values"][[-1]]-#[[2]]["Values"][[-(1+dt)]])/(#[[2]]["Times"][[-1]]-#[[2]]["Times"][[-(1+dt)]])}]
			(*ReplacePart[#,{2\[Rule](#\[LeftDoubleBracket]2\[RightDoubleBracket]["Values"]\[LeftDoubleBracket]-1\[RightDoubleBracket]-#\[LeftDoubleBracket]2\[RightDoubleBracket]["Values"]\[LeftDoubleBracket]-(1+dt)\[RightDoubleBracket])/(#\[LeftDoubleBracket]2\[RightDoubleBracket]["Times"]\[LeftDoubleBracket]-1\[RightDoubleBracket]-#\[LeftDoubleBracket]2\[RightDoubleBracket]["Times"]\[LeftDoubleBracket]-(1+dt)\[RightDoubleBracket])}]*)
		,
			Else,#
		]&/@sol
	];
	Return[res]
]


FinalDerivatives[sol_?NumericRuleListQ,___]:=ReplacePart[#,{1->#[[1]]',2->0}]&/@sol
