(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["FindPeriod"]


FindPeriod::usage=
"FindPeriod[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] returns the period of temporal \!\(\*
StyleBox[\"rulelist\", \"TI\"]\).";


FindPeriod[sol_,opts:OptionsPattern[]]:=Module[{var1,res,tmp},

Which[
	Head[sol[[1,2]]]===TemporalData,
	(* based on idea from bbgodfrey, http://mathematica.stackexchange.com/a/107741/6358 *)
	res=Length[DeleteDuplicates[Transpose[
		Map[(#/.sol)["Values"][[Max[-sol[[1,2]]["PathLength"],-OptionValue[MaxPeriod]];;]]&,sol[[All,1]]]],
		Norm[#1-#2]<10^-OptionValue[AccuracyGoal]+Norm[(#1-#2)/#1]*10^-OptionValue[PrecisionGoal]&]]
,
	Head[sol[[1,2]]]===InterpolatingFunction&&OptionValue[BasePeriod]=!=None,
	var1=sol[[1,1]];
	tmp={var1->TimeSeries[Table[{t,var1/.Slice[sol,t]},{t,InitialTime[sol],FinalTime[sol],OptionValue[BasePeriod]}]]};
	res=FindPeriod[tmp]*OptionValue[BasePeriod]
,
	True, (* else *)
	Return[];
];

Return[res]

];


Options[FindPeriod]={MaxPeriod->4,AccuracyGoal->5,PrecisionGoal->5,BasePeriod->None};
