(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["FindEigenvalues"]


FindEigenvalues::usage="FindEigenvalues[\!\(\*
StyleBox[\"mat\", \"TI\"]\), \!\(\*
StyleBox[\"ics\", \"TI\"]\)] finds eigenvalues near \!\(\*
StyleBox[\"ics\", \"TI\"]\).";


FindEigenvalues[m_,ics_?NumericListQ]:=If[Length[m]>2,
Quiet[Table[
	Check[Eigenvalues[m,1,Method->{"Arnoldi",Shift->ic}][[1]],ic,Eigenvalues::ssing]
,{ic,ics}],Eigenvalues::ssing],
Table[ic+Eigenvalues[m-ic IdentityMatrix[Length[m]],-1][[1]],{ic,ics}]
];



