(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["HighlightChanges"]


HighlightChanges::usage=
"HighlightChanges[True] turns on change highlighting. HighlightChanges[False] turns it off.";


HighlightChanges[bool_]:=If[bool==True,
	SetOptions[EvaluationNotebook[],{
	CellProlog:>(
		SelectionMove[EvaluationCell[],All,GeneratedCell];
		$oldoutput=ToExpression@*First/@Select[NotebookRead[SelectedCells[]],#[[2]]=="Output"&]
	),
	CellEpilog:>(
	SelectionMove[EvaluationCell[],All,GeneratedCell];
	$newoutput=ToExpression@*First/@Select[NotebookRead[SelectedCells[]],#[[2]]=="Output"&];
	If[($oldoutput/.x_Graphics:>ImageData@Rasterize[x,"Image"])=!=($newoutput/.x_Graphics:>ImageData@Rasterize[x,"Image"]),
		If[Head[$oldoutput]=!=Graphics&&Head[$oldoutput]=!=Graphics3D,
			Print[Style["Output change:",Red],"\nold=",$oldoutput]
		,
			Print[Style["Output change:",Red]]
		];
	];
	If[Length[$newoutput]!=0,SelectionMove[EvaluationCell[],After,CellGroup,2],SelectionMove[EvaluationCell[],After,Cell]]
	)
	}],
	SetOptions[EvaluationNotebook[],{CellProlog->{},CellEpilog->{}}]
];
