(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["InitialParameterValue"]
PackageExport["FinalParameterValue"]


InitialParameterValue::usage="InitialParameterValue[\!\(\*
StyleBox[\"x\", \"TI\"]\)] returns the smallest parameter value of ParametricDynamics or ParametricRuleList \!\(\*
StyleBox[\"x\", \"TI\"]\).";


InitialParameterValue[pd_ParametricDynamics]:=pd["Domain"][[1]];
InitialParameterValue[prl_?ParametricRuleListQ]:=InitialTime[prl/.if_InterpolatingFunction[par_]->if];


FinalParameterValue::usage="FinalParameterValue[\!\(\*
StyleBox[\"pd\", \"TI\"]\)] returns the largest parameter value of ParametricDynamics or ParametricRuleList \!\(\*
StyleBox[\"x\", \"TI\"]\).";


FinalParameterValue[pd_ParametricDynamics]:=pd["Domain"][[2]];
FinalParameterValue[prl_?ParametricRuleListQ]:=FinalTime[prl/.if_InterpolatingFunction[par_]->if];
