(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["InitialParameter"]
PackageExport["FinalParameter"]


InitialParameter::usage="InitialParameter[\!\(\*
StyleBox[\"x\", \"TI\"]\)] returns the smallest parameter value of ParametricDynamics or ParametricRuleList \!\(\*
StyleBox[\"x\", \"TI\"]\)\*
StyleBox[\(\!\(\*
StyleBox[\" \", \"TI\"]\) \)]as a rule list.";


InitialParameter[x_]:=ParameterName[x]->InitialParameterValue[x];


FinalParameter::usage="FinalParameter[\!\(\*
StyleBox[\"x\", \"TI\"]\)] returns the largest parameter value of ParametricDynamics or ParametricRuleList \!\(\*
StyleBox[\"x\", \"TI\"]\)\!\(\*
StyleBox[\" \", \"TI\"]\) as a rule list.";


FinalParameter[x_]:=ParameterName[x]->FinalParameterValue[x];
