(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["MyListLinePlot3D"]


MyListLinePlot3D::usage="MyListLinePlot3D[{{\!\(\*SubscriptBox[
StyleBox[\"x\", \"TI\"], 
StyleBox[\"1\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"y\", \"TI\"], 
StyleBox[\"1\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"z\", \"TI\"], 
StyleBox[\"1\", \"TR\"]]\)},{\!\(\*SubscriptBox[
StyleBox[\"x\", \"TI\"], 
StyleBox[\"2\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"y\", \"TI\"], 
StyleBox[\"2\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"z\", \"TI\"], 
StyleBox[\"2\", \"TR\"]]\)},\!\(\*
StyleBox[\"\[Ellipsis]\", \"TR\"]\)}] generates a 3D line plot of points with coordinates {\!\(\*SubscriptBox[
StyleBox[\"x\", \"TI\"], 
StyleBox[\"i\", \"TI\"]]\),\!\(\*SubscriptBox[
StyleBox[\"y\", \"TI\"], 
StyleBox[\"i\", \"TI\"]]\),\!\(\*SubscriptBox[
StyleBox[\"z\", \"TI\"], 
StyleBox[\"i\", \"TI\"]]\)}.
MyListLinePlot3D[{\!\(\*SubscriptBox[
StyleBox[\"data\", \"TI\"], 
StyleBox[\"1\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"data\", \"TI\"], 
StyleBox[\"2\", \"TR\"]]\),\!\(\*
StyleBox[\"\[Ellipsis]\", \"TR\"]\)}] plots several collections of points, by default in different colors.";


MyListLinePlot3D[arg_,opts___?OptionQ]:=Module[{listpointplot3dopts},
If[$VersionNumber>=12.3,(* use builtin ListLinePlot3D if available *)
	ListLinePlot3D[arg,opts],
	(* otherwise use homemade version *)
	(*Print["{opts}=",{opts}];*)
	listpointplot3dopts=FilterRules[{opts},Options[ListPointPlot3D]];
	(*Print["listpointplot3dopts=",listpointplot3dopts];*)
	If[Evaluate[Joined/.Flatten[{opts,Options[MyListLinePlot3D]}]]===False,
		ListPointPlot3D[arg,Sequence@@listpointplot3dopts],
		ListPointPlot3D[arg,Sequence@@listpointplot3dopts]/.Point[a___]:>{Thick,Line[a]}
	]
]
];


Options[MyListLinePlot3D]={Joined->True};



