(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["NEqual"]


NEqual::usage="NEqual[\!\(\*
StyleBox[\"x1\", \"TI\"]\), \!\(\*
StyleBox[\"x2\", \"TI\"]\)] tests if \!\(\*
StyleBox[\"x1\", \"TI\"]\) approximately equals \!\(\*
StyleBox[\"x2\", \"TI\"]\).";


NEqual[x1_,x2_,opts___?OptionQ]:=Module[{samethreshold},
	samethreshold=Evaluate[SameThreshold/.Flatten[{opts,Options[NEqual]}]];
	If[
		Dimensions[x1,AllowedHeads->"ListLike"]==Dimensions[x2,AllowedHeads->"ListLike"],
		Return[If[Norm[x1-x2]<samethreshold,True,False,False]],
		Message[NEqual::nedd];
		Return[False]
	];
];


Options[NEqual]={SameThreshold->10^-8};


NEqual::nedd="Arguments of NEqual have different dimensions.";



