(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["NumberedGridForm"]


NumberedGridForm::usage="NumberedGridForm[{\!\(\*SubscriptBox[
StyleBox[\"list\", \"TI\",\nFontSlant->\"Italic\"], \(1\)]\), \!\(\*
StyleBox[SubscriptBox[\"list\", \"2\"], \"TI\"]\), \[Ellipsis]}] formats \!\(\*SubscriptBox[
StyleBox[\"list\", \"TI\",\nFontSlant->\"Italic\"], \(1\)]\), \!\(\*
StyleBox[SubscriptBox[\"list\", \"2\"], \"TI\"]\), \[Ellipsis] in a table with numbers.";


(*NumberedGridForm[list_List]:=Grid[Transpose[{Range[Length[list]],list}],Alignment\[Rule]Left];*)
(*NumberedGridForm[lists__List,opts___?OptionQ]:=
	Grid[Transpose[{Range[Length[{lists}[[1]]]],lists}],Sequence@@Flatten[Join[{opts},Options[NumberedGridForm]]]];*)


NumberedGridForm[lists__,opts___?OptionQ]:=Module[{gridopts,header,nlists,res},

	gridopts=FilterRules[Flatten[Join[{opts},Options[NumberedGridForm]]],Options[Grid]];
	header=Header/.Flatten[Join[{opts},Options[NumberedGridForm]]];

	nlists=Length[{lists}];
	
	res=Transpose@Prepend[{lists},Range[Length[{lists}[[1]]]]];

	If[header===True,
		If[Unevaluated[{lists}]==={lists},
			header=Join[{"#"},Table["[["<>ToString[i]<>"]]",{i,nlists}]],
			header=Prepend[(Function[arg,ToString[Unevaluated[arg],InputForm],{HoldFirst}]/@Unevaluated[{lists}]),"#"]
		];
	];
	
	If[header=!=False,
		PrependTo[res,header];
		AppendTo[gridopts,Dividers->{False,2->True}];
	];
	
	Grid[res,Evaluate@@Sequence[gridopts]]
];

SetAttributes[NumberedGridForm,HoldAll]


Options[NumberedGridForm]={Header->False,Alignment->Left};



