(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ParametricDynamics"]


pdplots=Rasterize@Show[Table[Plot[0.1 i+0.2 i Sin[2\[Pi] t/(1+0.1 i)],{t,0,1+0.1 i},PlotStyle->Directive[Thickness[0.04],Hue[(i-2)/16]]],{i,1,13,3}],PlotRange->All,Axes->False,AspectRatio->1];


(*Format[ParametricDynamics[x_,opts___],StandardForm]:=SummaryForm[
	"ParametricDynamics",
	pdplots,{{"Variables: ",Keys[x[[1,2]]]},{"Domain: ",MinMax[x[[All,1]]]},{"Type: ",Type/.{opts}},{"Length: ",Length[x]}},
	3,StandardForm,x];*)


Format[ParametricDynamics[x_,opts___],StandardForm]:=SummaryForm[
	"ParametricDynamics",pdplots,
	{{"Variables: ",Quiet@Keys[x[[1]]]},{"Parameter: ",Parameter/.{opts}},{"Domain: ",Quiet@MinMax[ToExpression/@Keys[x]]},{"Type: ",Type/.{opts}},{"ModelType: ",ModelType/.{opts}},{"Length: ",Length[x]}},
	3,StandardForm,x];


(*Unprotect[System`Normal];
System`Normal[ParametricDynamics[x_,opts___]]:=x;
Protect[System`Normal];*)


ParametricDynamics[x_,opts___]["Variables"]:=Keys[x[[1]]];
ParametricDynamics[x_,opts___]["Keys"]:=Keys[x];
ParametricDynamics[x_,opts___]["Coordinates"]:=ToExpression/@Keys[x];
ParametricDynamics[x_,opts___]["Domain"]:=MinMax[ToExpression/@Keys[x]];
ParametricDynamics[x_,opts___]["Parameter"]:=Parameter/.{opts};
ParametricDynamics[x_,opts___]["Type"]:=Type/.{opts};
ParametricDynamics[x_,opts___]["ModelType"]:=ModelType/.{opts};
ParametricDynamics[x_,opts___][par_?NumericQ]:=ParameterSlice[ParametricDynamics[x,opts],par]
ParametricDynamics[x_,opts___]["Options"]:=opts;
