(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ParameterName"]


ParameterName::usage="ParameterName[\!\(\*
StyleBox[\"x\", \"TI\"]\)] returns the parameter name of ParametricRuleList or ParametricDynamics \!\(\*
StyleBox[\"x\", \"TI\"]\).";


ParameterName[prl_?ParametricRuleListQ]:=prl[[1,2,1]];
ParameterName[pd_ParametricDynamics]:=ToExpression@pd["Parameter"];



