(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["PlotVector"]


PlotVector::usage="PlotVector[\!\(\*
StyleBox[\"vec\", \"TI\"]\)] plots a vector from the origin.
PlotVector[\!\(\*
StyleBox[\"vec\", \"TI\"]\), \!\(\*
StyleBox[\"pt\", \"TI\"]\)] plots a vector starting at \!\(\*
StyleBox[\"pt\", \"TI\"]\).";


PlotVector[vec_,ptin_List:{},opts___?OptionQ]:=Module[{plotstyle,dim,pt},

(* handle options *)
plotstyle=Evaluate[PlotStyle/.Flatten[{opts,Options[PlotVector]}]];
dim=Length[vec];

If[ptin==={},pt=ZeroVector[dim],pt=ptin];

Which[
	dim==2,
	Graphics[Join[Flatten[{plotstyle}],{Arrow[{pt,pt+vec}]}]],
	dim==3,
	Graphics3D[Join[Flatten[{plotstyle}],{Arrow[{pt,pt+vec}]}]]
]
]


Options[PlotVector]={PlotStyle->Black};



