(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ReplaceRHS"]
PackageExport["ReplaceLHS"]


ReplaceRHS::usage="ReplaceRHS[\!\(\*
StyleBox[\"eqn\", \"TI\"]\), \!\(\*
StyleBox[\"rule\", \"TI\"]\)] applies replacement rule \!\(\*
StyleBox[\"rule\", \"TI\"]\) to the right-hand side of \!\(\*
StyleBox[\"eqn\", \"TI\"]\).";
ReplaceLHS::usage="ReplaceLHS[\!\(\*
StyleBox[\"eqn\", \"TI\"]\), \!\(\*
StyleBox[\"rule\", \"TI\"]\)] applies replacement rule \!\(\*
StyleBox[\"rule\", \"TI\"]\) to the left-hand side of \!\(\*
StyleBox[\"eqn\", \"TI\"]\).";


ReplaceRHS[eqn_,rules_]:=eqn/.(Equal[lhs_,rhs_]:>Equal[lhs,rhs/.Flatten@rules]);
ReplaceLHS[eqn_,rules_]:=eqn/.(Equal[lhs_,rhs_]:>Equal[lhs/.Flatten@rules,rhs]);

(* make Listable over eqns *)
ReplaceRHS[eqns_List,rules_]:=ReplaceRHS[#,rules]&/@eqns;
ReplaceLHS[eqns_List,rules_]:=ReplaceLHS[#,rules]&/@eqns;
