(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["RouthHurwitzCriteria"]


RouthHurwitzCriteria::usage=
"RouthHurwitzCriteria[\!\(\*
StyleBox[\"matrix\", \"TI\"]\)] gives the modified Routh-Hurwitz stability criteria (up to 3x3).";


RouthHurwitzCriteria[a_?MatrixQ]:=Module[{c3},
	If[!SquareMatrixQ[a],Message[RouthHurwitzCriteria::nonsq];Return[a]];
	Which[
		Length[a]==1,
		Return[Piecewise[{{True,a[[1,1]]<0},{False,a[[1,1]]>0}},Indeterminate]],
		Length[a]==2,
		Return[Piecewise[{{True,Tr[a]<0&&Det[a]>0},{False,Tr[a]>0||Det[a]<0}},Indeterminate]],
		Length[a]==3,
		c3=Det[{{a[[1,1]]+a[[2,2]],a[[2,3]],-a[[1,3]]},{a[[3,2]],a[[1,1]]+a[[3,3]],a[[1,2]]},{-a[[3,1]],a[[2,1]],a[[2,2]]+a[[3,3]]}}];
		Return[Piecewise[{{True,Tr[a]<0&&Det[a]<0&&c3<0},{False,Tr[a]>0||Det[a]>0||c3>0}},Indeterminate]],
		Length[a]>3,
		Message[RouthHurwitzCriteria::toobig];Return[a]
	]
];
