(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["RuleListAdd"]
PackageExport["RuleListSubtract"]
PackageExport["RuleListMultiply"]
PackageExport["RuleListDivide"]


RuleListAdd::usage=
"RuleListAdd[\!\(\*
StyleBox[\"rulelist1\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\)] adds corresponding elements of two rulelists.
RuleListAdd[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\), \!\(\*
StyleBox[\"x\", \"TI\"]\)] or RuleListAdd[\!\(\*
StyleBox[\"x\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] adds number \!\(\*
StyleBox[\"x\", \"TI\"]\) to all elements of rulelist \!\(\*
StyleBox[\"rulelist\", \"TI\"]\).";


RuleListAdd[a_?RuleListQ,b_?RuleListQ]:=Normal[Merge[{a,b},Total]];
RuleListAdd[a_?RuleListQ,x_?NumericQ]:=Normal[Merge[a,x+#[[1]]&]];
RuleListAdd[x_?NumericQ,a_?RuleListQ]:=Normal[Merge[a,x+#[[1]]&]];


RuleListSubtract::usage=
"RuleListSubtract[\!\(\*
StyleBox[\"rulelist1\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\)] subtracts corresponding elements of \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\) from \!\(\*
StyleBox[\"rulelist1\", \"TI\"]\).";


RuleListSubtract[a_?RuleListQ,b_?RuleListQ]:=RuleListAdd[a,RuleListMultiply[b,-1]];


RuleListMultiply::usage=
"RuleListMultiply[\!\(\*
StyleBox[\"rulelist1\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\)] multiplies corresponding elements of rulelists.
RuleListMultiply[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\), \!\(\*
StyleBox[\"x\", \"TI\"]\)] or RuleListMultiply[\!\(\*
StyleBox[\"x\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] multiplies elements of rulelist \!\(\*
StyleBox[\"rulelist\", \"TI\"]\) by number \!\(\*
StyleBox[\"x\", \"TI\"]\).";


RuleListMultiply[a_?RuleListQ,x_?NumericQ]:=Normal[Merge[a,x*#[[1]]&]];
RuleListMultiply[x_?NumericQ,a_?RuleListQ]:=Normal[Merge[a,x*#[[1]]&]];
RuleListMultiply[a_?RuleListQ,b_?RuleListQ]:=Normal[Merge[{a,b},Apply[Times]]];


RuleListDivide::usage=
"RuleListDivide[\!\(\*
StyleBox[\"rulelist1\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\)] divides corresponding elements of \!\(\*
StyleBox[\"rulelist1\", \"TI\"]\) by \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\).
RuleListDivide[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\), \!\(\*
StyleBox[\"x\", \"TI\"]\)] or RuleListDivide[\!\(\*
StyleBox[\"x\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] divides elements of rulelist \!\(\*
StyleBox[\"rulelist\", \"TI\"]\) by number \!\(\*
StyleBox[\"x\", \"TI\"]\) or vice versa.";


RuleListDivide[a_?RuleListQ,x_?NumericQ]:=Normal[Merge[a,#[[1]]/x&]];
RuleListDivide[x_?NumericQ,a_?RuleListQ]:=Normal[Merge[a,x/#[[1]]&]];
RuleListDivide[a_?RuleListQ,b_?RuleListQ]:=Normal[Merge[{a,b},Apply[Divide]]];
