(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["RuleListDistance"]


RuleListDistance::usage=
"RuleListDistance[\!\(\*
StyleBox[\"rulelist1\", \"TI\"]\), \!\(\*
StyleBox[\"rulelist2\", \"TI\"]\)] gives the distance between two rule lists.
RuleListDistance[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] gives the distance between a rule list and the origin.";


RuleListDistance[in1_?NumericRuleListQ,in2:(_?NumericRuleListQ):{},opts___?OptionQ]:=

Module[{
(* options *)
distancefunction=Evaluate[DistanceFunction/.Flatten[{opts,Options[RuleListDistance]}]],
weights=Evaluate[Weights/.Flatten[{opts,Options[RuleListDistance]}]],
(* other variables *)
list1,list2},

list1=RuleListMultiply[in1,weights];
If[in2!={},
	list2=RuleListMultiply[in2,weights],
	list2=RuleListMultiply[in1,0]
];

Return[distancefunction[Sort[list1][[All,2]],Sort[list2][[All,2]]]]
];


Options[RuleListDistance]={DistanceFunction->EuclideanDistance,Weights->{}};
