(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["RuleListComplement"]


RuleListComplement::usage=
"RuleListComplement[\!\(\*SubscriptBox[
StyleBox[\"e\", \"TI\"], 
StyleBox[\"all\", \"TI\"]]\),\!\(\*SubscriptBox[
StyleBox[\"e\", \"TI\"], 
StyleBox[\"1\", \"TR\"]]\),\!\(\*SubscriptBox[
StyleBox[\"e\", \"TI\"], 
StyleBox[\"2\", \"TR\"]]\),\!\(\*
StyleBox[\"\[Ellipsis]\", \"TR\"]\)] gives the elements in \!\(\*
StyleBox[SubscriptBox[\"e\", \"all\"], \"TI\"]\) whose variables don't match any of the \!\(\*
StyleBox[SubscriptBox[\"e\", \"i\"], \"TI\"]\).";


RuleListComplement[all_?RuleListQ,i__?RuleListQ]:=Complement[all,i,SameTest->(First[#1]===First[#2]&)];
