(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["RuleListTweak"]


RuleListTweak::usage=
"RuleListTweak[\!\(\*
StyleBox[\"point\", \"TI\"]\), \!\(\*
StyleBox[\"var\", \"TI\"]\), \!\(\*
StyleBox[\"h\", \"TI\"]\)] perturbs variable \!\(\*
StyleBox[\"var\", \"TI\"]\) in rulelist \!\(\*
StyleBox[\"point\", \"TI\"]\) by \!\(\*
StyleBox[\"h\", \"TI\"]\).
RuleListTweak[\!\(\*
StyleBox[\"point\", \"TI\"]\), \!\(\*
StyleBox[\"vars\", \"TI\"]\), \!\(\*
StyleBox[\"h\", \"TI\"]\)] perturbs variables \!\(\*
StyleBox[\"vars\", \"TI\"]\) in rulelist \!\(\*
StyleBox[\"point\", \"TI\"]\) by \!\(\*
StyleBox[\"h\", \"TI\"]\).";


RuleListTweak[point_?RuleListQ,var_Symbol,h_]:=Append[Select[point,#[[1]]=!=var&],var->((var/.point)+h)];
RuleListTweak[point_?RuleListQ,var_Subscript,h_]:=Append[Select[point,#[[1]]=!=var&],var->((var/.point)+h)];
RuleListTweak[point_?RuleListQ,var_List,h_List]:=Join[Select[point,!MemberQ[var,#[[1]]]&],#->((#/.point)+h[[Position[var,#][[1,1]]]])&/@var];
