(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["SimplifyLogE"]


SimplifyLogE::usage=
"SimplifyLogE is a replacement rule that simplifies Log[\!\(\*
StyleBox[\"a\", \"TI\"]\) \!\(\*SuperscriptBox[\(E\), 
StyleBox[\"x\", \"TI\"]]\)] to Log[\!\(\*
StyleBox[\"a\", \"TI\"]\)]+\!\(\*
StyleBox[\"x\", \"TI\"]\).";


SimplifyLogE=Log[(a_:1) E^x_]:>x+Log[a];
