(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["SummaryForm"]


SummaryForm[name_,icon_,infos_,maxInfos_,form_,expr_]:=
RawBoxes@Quiet@Module[{shown,hidden},
	(*convert info-table into summary items*)
	{shown,hidden}=Map[BoxForm`MakeSummaryItem[#,form]&,TakeDrop[infos,maxInfos],{2}];
	(*arrange the summary and make sure the label is gray (therefore StyleBox)*)
	StyleBox[BoxForm`ArrangeSummaryBox[name,expr,Deploy@Show[
		icon,
		(*avoid gray background before mouse-over*)Background->White,
		(*set standard image size*)ImageSize->Dynamic[{Automatic,3.5 CurrentValue["FontCapHeight"]/AbsoluteCurrentValue[Magnification]}]],
		shown,hidden,form,
		(*formatted object should be uasable as input*)
		"Interpretable"->True],"NonInterpretableSummary"]
];



