(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["TemporalCorrelation"]


TemporalCorrelation::usage=
"TemporalCorrelation[\!\(\*
StyleBox[\"f1\", \"TI\"]\), \!\(\*
StyleBox[\"f2\", \"TI\"]\), \!\(\*
StyleBox[\"var\", \"TI\"]\)] gives the correlation of \!\(\*
StyleBox[\"f1\", \"TI\"]\) and \!\(\*
StyleBox[\"f2\", \"TI\"]\) with respect to \!\(\*
StyleBox[\"var\", \"TI\"]\)\!\(\*
StyleBox[\" \", \"TI\"]\)(default \!\(\*
StyleBox[\"var\", \"TI\"]\)=\!\(\*
StyleBox[\"t\", \"TI\"]\)).
TemporalCorrelation[\!\(\*
StyleBox[\"f1\", \"TI\"]\), \!\(\*
StyleBox[\"f2\", \"TI\"]\), {\!\(\*
StyleBox[\"var\", \"TI\"]\), \!\(\*
StyleBox[\"varmin\", \"TI\"]\), \!\(\*
StyleBox[\"varmax\", \"TI\"]\)}] ranges from \!\(\*
StyleBox[\"varmin\", \"TI\"]\) to \!\(\*
StyleBox[\"varmax\", \"TI\"]\).
TemporalCorrelation[\!\(\*
StyleBox[\"rulelist\", \"TI\"]\)] threads over \!\(\*
StyleBox[\"rulelist\", \"TI\"]\) to give variances and covariances.";


(* thread over rule lists *)
TemporalCorrelation[f_?RuleListQ,varsin_List:{All},opts___?OptionQ]:=Module[{vars,pairs},
(*Print["threading 1"];*)
	If[varsin=={All},vars=Keys[f],vars=varsin];
(*Print["vars=",vars];*)
	pairs=Subsets[vars,{2}];
	Return[
		Table[Cor[Evaluate@@Sequence[pair]]->TemporalCovariance[Evaluate@@Sequence[pair/.f],opts]/
			Sqrt[TemporalVariance[pair[[1]]/.f,opts]*TemporalVariance[pair[[2]]/.f,opts]]
	,{pair,pairs}]]
];

TemporalCorrelation[f1_,f2_,rest___]:=
	TemporalCovariance[f1,f2,rest]/Sqrt[TemporalVariance[f1,rest]*TemporalVariance[f2,rest]];



