(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ExtractInvaders"]
PackageExport["DeleteInvaders"]


ExtractInvaders::usage=
"ExtractInvaders[\!\(\*
StyleBox[\"list\", \"TI\"]\)] extracts invaders (with subscript 0) from \!\(\*
StyleBox[\"list\", \"TI\"]\).";

DeleteInvaders::usage=
"DeleteInvaders[\!\(\*
StyleBox[\"list\", \"TI\"]\)] removes invaders (with subscript 0) from \!\(\*
StyleBox[\"list\", \"TI\"]\).";


ExtractInvaders[list_?RuleListQ]:=FilterRules[list,Subscript[_, 0]->_];


DeleteInvaders[list_?RuleListQ]:=DeleteCases[list,Subscript[_,0,___]->_];
