(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



Package["EcoEvo`"]
PackageExport["ExtractPeriod"]


ExtractPeriod::usage="ExtractPeriod[\!\(\*
StyleBox[\"in\", \"TI\"]\)] returns FinalTime[in] for ContinuousTime models and FinalTime[in]+1 for DiscreteTime models.";


ExtractPeriod[in_?TemporalRuleListQ]:=
Which[
	modeltype=="ContinuousTime",
	per=FinalTime[in],
	modeltype=="DiscreteTime",
	per=FinalTime[in]+1
];



